name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: |
          npm run build:cjs
          npm run build:esm

      - name: Verify build outputs
        run: |
          if [ ! -d "dist/cjs" ]; then
            echo "CJS build is missing"
            exit 1
          fi
          if [ ! -d "dist/esm" ]; then
            echo "ESM build is missing"
            exit 1
          fi
          if [ ! -d "dist/types" ]; then
            echo "Types are missing"
            exit 1
          fi

      - name: Pack package
        run: npm pack

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
